### ISSUE TITLE
Inverted mouse when rotating the screen in Raspberry Pi OS

### ISSUE THREAD

**Issue by steveiliop56** [WayfireWM/wayfire#2349] opened 2024-05-08 11:03 UTC
**Describe the bug**
So I have a raspberry pi 5 with a small display connected to it (the hyperpixel 4) and I have rotated the screen to the right through the Screen Configuration utility. The problem is that when I try to access the desktop through wayvnc the mouse is inverted. In an issue in wayvnc the creator said its probably a wayfire bug https://github.com/any1/wayvnc/issues/294 when I looked in this issue https://github.com/WayfireWM/wayfire/issues/1957 it closed saying it's a wlroots problem but this issues seems to have been fixed in wlroots. So where is the actual problem? Is there a temporary fix to this? 

**To Reproduce**
1. Rotate the screen on Raspberry Pi OS
2. Try to access the desktop through wayvnc and you will see that the mouse is inverted

**Expected behavior**
The mouse shouldn't be inverted.

**Screenshots or stacktrace**
https://github.com/WayfireWM/wayfire/assets/106091011/168c2d20-5a7f-4e2d-95d9-842e9f65cd1a
(you can see a small dot moving that's my actual mouse)

**Wayfire version**
0.7.5

**Comment by ammen99** [comment] 2024-05-08 11:13
I believe this is a duplicate of #1283. As a workaround, you can try mapping the virtual pointer devices to the output, that should fix the rotation, the config is the same as for ex. when binding a touchscreen device to an output: https://github.com/WayfireWM/wayfire/wiki/Configuration#input-device-specific-options

**Closed by ammen99** 2024-05-08 11:13 UTC
Labels: bug

**Comment by ammen99** [comment] 2024-06-20 13:46
If you run Wayfire with the `-d` flag, does it print in the log (printed on stdout) that it has mapped the input device to the output successfully? Also it coudl be a wlroots bug, RPi uses an outdated wayfire/wlroots version so if you can I'd suggest trying to compile a newer version and see whether it doesn't work.

Also keep in mind that you need to map the virtual pointer (created by wayvnc on the target wayfire, not from where you're controlling it). See also https://github.com/WayfireWM/wayfire/issues/1283
