### ISSUE TITLE
how to invoke shortcuts from terminal 

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wayfire#325] opened 2019-10-30 17:38 UTC
how can i invoke wayfire shortcut from terminal.
ex.
i want to leave wayfire session (logout) using 
terminal.
and want to create a logout.desktop
file and add as an launcher in wf-panel.
in x
 xdotool can do this with 

xdotool key ctrl + alt + backspace

also i want to use libinput-gestures to invoke wayfire keyboard shortcuts with touchpad gestures.

how to invoke various wayfire functions with terminal.

in kwin its executed this way

qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Switch to Next Desktop"

**Comment by soreau** [comment] 2019-10-30 18:52
You can write evdev events using a script like [this](https://pastebin.com/raw/m3niU9zF). To trigger plugin bindings as user, there would need to be some interface, maybe dbus or a custom protocol that wouldn't require root.

**Comment by librewish** [comment] 2019-11-01 04:46
you wont mind ?
if i make a 
linux spin with wayfire 
and 
name it wayfire linux.
it will be based on manjaro unstable branch.
i am going to use
gnome apps with it.
and cmst for network 
and no gnome control centre.

**Comment by ammen99** [comment] 2019-11-01 06:46
@librewish, wayfire is open-source and MIT licensed, you can do almost anything you want :) And I am also fine with you using the name. Only please specify that your project is made by yourself,  and not us.

**Comment by librewish** [comment] 2019-11-01 06:53
okay thanks.
here is a screenshot of how it will look.
![slurped-2019-11-01-12:20:47](https://user-images.githubusercontent.com/44837339/68007710-66bbdc80-fca2-11e9-9844-7399f332eade.png)

**Comment by librewish** [comment] 2019-11-21 14:49
> You can write evdev events using a script like [this](https://pastebin.com/raw/m3niU9zF). To trigger plugin bindings as user, there would need to be some interface, maybe dbus or a custom protocol that wouldn't require root.

adding the user to plugdev group 
eliminates the need for root access to use the script.

also i found
ydotool 

https://github.com/ReimuNotMoe/ydotool

which does the xdotool job.

**Comment by ammen99** [comment] 2020-08-01 06:46
Duplicate of #49

**Closed by ammen99** 2020-08-01 06:46 UTC

**Comment by damianatorrpm** [comment] 2020-08-01 07:23
@librewish Checkout https://github.com/damianatorrpm/wayfire-plugin_dbus_interface
if you want to implement xdotool functionality there is an open issue and it shouldn't be too hard.

**Comment by ammen99** [comment] 2020-08-01 07:52
@damianatorrpm My first impression was that they wanted to have a way to trigger activators from cmdline.

**Comment by damianatorrpm** [comment] 2020-08-01 08:44
@ammen99 that's one way to achieve this, they could of course do this , or send  ctrl + alt + backspace via an xdotool like command 'gdbus call --sesion org.wayland.compositor / org.wayland.compositor.send_keys ['ctrl', 'alt', 'backspace']
whatever they feel more comfortable with

**Comment by AdrianVovk** [comment] 2020-08-01 12:26
@damianatorrpm Having to send keys means that the external program would have to parse wayfire's config and then decide which keys to send based on that. No good
