### ISSUE TITLE
Tooltip flicker

### ISSUE THREAD

**Issue by mrsteve0924** [WayfireWM/wayfire#2141] opened 2024-02-16 04:13 UTC
**Describe the bug**
When hovering over widgets in wf-panel the tooltip will flicker intensely when mouse moves over tooltip box

I first noticed it with the Teams chromium web app.  It is not happening with Chromium though.  
Other place it happens consistently is wf-panel with the window-list widget and system tray.
I couldn't reproduce in firefox, thunar and thunderbird

**Wayfire version**
this started when i updated to commit 7388778. Previously I was on d6abead.

**Comment by soreau** [comment] 2024-02-18 17:00
This sounds like a duplicate of #722 and #1765.

**Comment by ammen99** [comment] 2024-03-01 20:34
@mrsteve0924 I cannot reproduce this bug in wf-panel. Do you use fcitx5 per chance, or some other input method? If yes, try updating to latest master. Otherwise, please record a quick screenshot of the problem so that I can see exactly what is happening, maybe I am doing the wrong steps here.

**Comment by ammen99** [comment] 2024-03-01 20:37
Here is a small recording of the area of the window-list on my machine: 
![flicker](https://github.com/WayfireWM/wayfire/assets/6287487/bba6288b-0121-4197-b705-81e6d45d421b)

**Comment by mrsteve0924** [comment] 2024-03-01 22:37
I updated wayfire to latest commit 27ddca3 and i get the flicker.     wf-shell i am on commit 892ce5c. i dont have fcitx5 installed. 

https://imgur.com/Y2zkjb5
https://imgur.com/Q4vx0Hm
https://imgur.com/qg6c5B6

**Comment by ammen99** [comment] 2024-03-02 08:16
@mrsteve0924 Thanks for finding out the root cause, I found the bug in the shadow calculation code for popups. I'll ping you soon with a fix.

**Comment by ammen99** [comment] 2024-03-02 08:46
See #2170

**Closed** 2024-03-02 08:57 UTC
Labels: bug

**Comment by kode54** [comment] 2024-03-03 10:26
Thanks again! Sorry if my IRC report wasn't helpful.
