### ISSUE TITLE
Disable Touchpad completely

### ISSUE THREAD

**Issue by franzmondlichtmann** [WayfireWM/wayfire#1478] opened 2022-05-13 06:42 UTC
In the wiki it is stated that you can disable touchpad when using a mouse or when typing at the same time.
Apparently there is no way to disable the touchpad completely.
Furthermore a method to assign a key to toogle the touchpad would be great.

**Comment by ammen99** [comment] 2024-03-08 12:48
Duplicate of #871

**Closed by ammen99** 2024-03-08 12:48 UTC
Labels: enhancement
