### ISSUE TITLE
Memory leak with blur plugin

### ISSUE THREAD

**Issue by travankor** [WayfireWM/wayfire#1247] opened 2021-07-21 15:01 UTC
**Describe the bug**
Wayfire leaks memory with the blur plugin enabled.

**To Reproduce**
1. Enable [blur] plugin
2. Drag a view around *or* create several views and then close all views
3. Wayfire leaks memory

**Expected behavior**
Wayfire does not leak memory with the blur plugin enabled.

**Video**
https://0x0.st/-Vwq.mp4
https://0x0.st/-VwT.mp4

**Wayfire version**
0.7.2 and -git

**Comment by vggscqq** [comment] 2021-09-28 14:58
What am I do wrong? Maybe wobbling effect leaks?
Video: https://0x0.st/-YIA.mp4

**Comment by vggscqq** [comment] 2021-09-28 15:22
Nope. Wobble module has no effect on memory leakage.
Video: https://0x0.st/-YI2.mp4

**Comment by h1w** [comment] 2021-09-28 15:45
No memory leak

Arch Linux. Wayfire 0.7.2-1
PC:
CPU: Intel i5-3470(4) 3.6GHz
GPU: AMD ATI Radeon RX 570
RAM: 8 Gb

**Comment by Javyre** [comment] 2021-09-28 16:47
Cannot reproduce either:

Wayfire master
Kernel: 5.13.19_1
CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz 
GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT
Memory: 15930MiB

**Comment by soreau** [comment] 2021-09-28 17:10
It doesn't seem to happen here:

Wayfire master fa6a505d
5.11.0
Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
AMD Radeon (TM) RX 460 Graphics (POLARIS11, DRM 3.40.0, 5.11.0, LLVM 11.0.0)
Mesa 21.2.0-devel git-390722620e
16359988 kB

@travankor Can you try again with latest wayfire and foot? Closing for now, open again if it is still happening.

**Closed by soreau** 2021-09-28 17:10 UTC
Labels: bug
