### ISSUE TITLE
Add window swapping to simple tile

### ISSUE THREAD

**Issue by LuxLucian** [WayfireWM/wayfire#1122] opened 2021-03-16 16:01 UTC
When dragging one tiled window to the center of another, have it swap places with the targeted window.
The boxes that appear when dragging tiled windows imply that something like this would be the case, but instead nothing happens. It would make rearranging windows less tedious in some cases too.

**Comment by ammen99** [comment] 2021-03-21 20:14
This is duplicate of #681 

If you want to use this feature, you can apply #1071, it already has this feature implemented (but lacks others which is why it isn't merged yet)

**Closed by ammen99** 2021-03-21 20:14 UTC
Labels: enhancement
