### ISSUE TITLE
Wayfire un-scales the display when reloading its configuration

### ISSUE THREAD

**Issue by jkatzmewing** [WayfireWM/wayfire#1235] opened 2021-07-07 15:06 UTC
**Describe the bug**
When configured for HiDPI scaling, Wayfire will unscale the display if forced to reload its configuration e.g. by making changes in the configuration manager. The scaling factor isn't removed from wayfire.ini; it's just un-applied, and can't be reapplied without exiting and restarting Wayfire.

**To Reproduce**
1. Edit wayfire.ini to enable scaling, e.g.

```
[output]
mode = auto
position = auto
scale = 2.000000
transform = normal
```
2. Restart Wayfire to apply the scaling.
3. Open the Wayfire configuration manager.
4. Make any change to the settings of any plugin. The scaling factor will be unapplied instantly.

**Expected behavior**
A scaling factor set in wayfire.ini should not be unapplied when making changes to unrelated parts of the configuration.

**Wayfire version**
wayfire-0.7.1-2.fc34.x86_64 and wayfire-config-manager-0.7.0-1.fc34.x86_64 on Fedora 34, on a Surface Pro 3.

**Comment by soreau** [comment] 2021-07-07 15:17
This is a duplicate of [wcm#29](https://github.com/WayfireWM/wcm/issues/29). See [this comment](https://github.com/WayfireWM/wcm/issues/29#issuecomment-868206445) about a workaround that was recently added to help this case.

**Closed** 2023-11-29 21:55 UTC
Labels: bug
