### ISSUE TITLE
[src/output/plugin-loader.cpp:106] error loading plugin: /usr/lib/wayfire/libtile.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wayfire#348] opened 2019-12-04 05:41 UTC
[src/output/plugin-loader.cpp:106] error loading plugin: /usr/lib/wayfire/libtile.so: cannot open shared object file: No such file or directory

when tile plugin is activated from wcm
i cant use tile plugin i think its renamed simple-tile

**Comment by soreau** [comment] 2019-12-04 05:57
wcm assumes the section name will be the same as the grab_interface name.

@ammen99 Is there any reason for the difference in names here?

**Comment by librewish** [comment] 2019-12-04 05:59
also when i set simple-tile in wayfire.ini
the tile plugin is not working

**Comment by soreau** [comment] 2019-12-04 06:25
> @ammen99 Is there any reason for the difference in names here?

My mistake, they are the same. I pushed a wcm commit that should fix it. Don't forget to uninstall wcm first or remove $prefix/share/wayfire/metadata/tile.xml manually.

**Comment by librewish** [comment] 2019-12-04 07:36
updated wcm

now the error is gone but tiling is not working

**Comment by ammen99** [comment] 2019-12-04 08:13
Can you check whether there are error messages in the log? Preferably send the whole output here.

**Comment by librewish** [comment] 2019-12-04 08:44
no error shown tile is active but its not working
![screenshot-2019-12-04-14:12:47](https://user-images.githubusercontent.com/44837339/70127078-541d3480-16a0-11ea-835d-d49835952eb6.png)

**Comment by ammen99** [comment] 2019-12-04 08:46
Have you updated WCM? We have an icon for tile, and your WCM doesn't have one.

**Comment by librewish** [comment] 2019-12-04 08:48
its updated
with your new commit 
icon is gone

**Comment by ammen99** [comment] 2019-12-04 09:14
Oh I think know what the problem is. @librewish Can you enable matcher, and put it **before** the simple-tile plugin in the plugin list?

**Comment by librewish** [comment] 2019-12-04 09:18
yes doing this and logot login 
now tiling works

**Comment by librewish** [comment] 2019-12-04 09:20
but why is this necessary?

**Comment by ammen99** [comment] 2019-12-04 09:20
So simple-tile now requires matcher to work. I guess we need to put this in WCM somehow, and also give error messages in Wayfire.

**Comment by ammen99** [comment] 2019-12-04 09:21
> but why is this necessary?

Matcher is used because you can only tile some windows by default. For example, I only want to tile terminals by default, and I have `tile_by_default = app-id is kitty` in my config file.

**Comment by ammen99** [comment] 2020-03-25 20:57
Will be fixed once #398 is fixed, so closing this issue in favor of the other issue.

**Closed by ammen99** 2020-03-25 20:57 UTC
