### ISSUE TITLE
Map output to workspaces

### ISSUE THREAD

**Issue by ghost** [WayfireWM/wayfire#1211] opened 2021-06-10 02:33 UTC
Hello, I've been playing around with Wayfire for the past few days (trying to see if I can switch to it with my workflow), and so far it's fantastic. However, I'm curious if I can get a feature I've become accustomed to, working here as well.

Previously, I used XFCE and a few custom scripts to move windows around (tiling them and moving them between monitors). The tiling is mostly there (in my scripts I'd dynamically tile the windows based on its current position and the keystrokes, i.e. currently tiled to the bottom-left, keystroke up, now occupies left half of the screen, keystroke up again, now at the top-left), but I can get mostly the same functionality with the Wayfire grid plugin.

I also used to 'jump' windows up/down/left/right to whichever output was in that general direction. I think I can accomplish much the same with Wayfire using the output-switcher plugin. However, I've just now looked into the vast support Wayfire has for workspaces and am now wondering if there is a more effective way to add this to my workflow.

So to the point of this issue. Is there a method wherein I could map a newly connected output into the workspaces already established? i.e. A current 3x3 workspace grid, connect another output, this output automatically displays whatever is on workspace (1,0)?

P.S. It bears repeating, fantastic job on Wayfire. Irrelevant of if I can get the above working, I'll be a Wayfire user, as I've become to enamored with how smooth everything is.

**Comment by Javyre** [comment] 2021-06-10 03:26
> Is there a method wherein I could map a newly connected output into the workspaces already established?

Not that I know of. Outputs cannot share the same workspace grid. In order to display (1,0) in the new output, you would have to move all the views to that output. @ammen99 probably has something to add to this conversation though.

**Comment by ammen99** [comment] 2021-06-10 05:26
@simplejack-src Hi, you have not missed anything, there is no built-in functionality in Wayfire for what you are trying to achieve. You'll have to delve into custom plugins, but luckily for you I have already written a very similar plugin (which transfers views from all workspaces). The plugin is described in detail in a [blog post here](https://wayfire.org/2020/04/10/Writing-Plugins.html), although the code in the blog might be a bit outdated. You can find the latest code [here](https://github.com/ammen99/wayfire-plugins/blob/master/src/primary-monitor-switch.cpp).

**Comment by simplejack-src** [comment] 2021-06-10 15:02
@ammen99 I think that plugin would achieve the first part (output connected, move windows to new output). However, upon further thought I'm now thinking I'm going about this the wrong way.

Wayfire is setup with the assumption that each output maintains it's own environment (own set of plugins, own set of workspaces). I'd be changing that assumption to one set of workspaces for all (i.e. each monitor is just a glimpse into a global workspace grid). While I can see a benefit to this, I'm wondering if it would be an uphill battle of maintainability/compatibility to go this route? Perhaps it would be better if I looked into adapting my workflow to use the discreet workspaces provided by each output...

**Comment by ammen99** [comment] 2021-06-10 15:26
@simplejack-src Transferring views from one output to another when a new output is connected should be pretty well supported. Also, if you want to synchronize workspaces on both outputs, this should be rather simple too - just make a plugin which switches the workspaces on both outputs simultaneously (you don't even have to write much code, just call the relevant bindings of vswitch on all outputs). Both of these things are possible by design and I don't think it would be really an uphill battle, especially considering that I am using primary-monitor-switch in my daily workflow :)

However, if you want to really have a global grid spanning all outputs and having things like views sitting between outputs, etc., then this is possible, but indeed it goes against Wayfire's design and it will be harder to keep up with upstream. You'd also probably have to patch several plugins, adding even more maintenance burden.

**Comment by simplejack-src** [comment] 2021-06-10 21:24
@ammen99 Thank-you for the run down. I don't think I'll implement this at this time or perhaps ever depending on if I think I would still use it. My current workflow doesn't use workspaces (I always just used whatever was on each screen, stack up windows as necessary and alt-tab as I change windows). However, everyone seems to be ranting about how great workspaces are (they categorize things so nicely!) so I've been trying to add them to my workflow. Which unlike other DE's I've tried (GNOME, XFCE, LXDE, etc.) Wayfire has really nice exposure to them (the Expo plugin in particular is so simple and quick I don't know why it hasn't been implemented by others).

I might look into modifying the output-switcher plugin though (after I get my desktop/shell all setup with Wayfire), see if I can modify it to expose activators switch outputs depending on where the output is positioned, i.e. switch to output that is positioned above/beside current output (possibly with windows). Which after a quick look at the source seems pretty simple (loop through outputs, track next X or Y position that is less/greater (depending on activator) then current output).

**Closed** 2024-02-26 09:54 UTC
Labels: enhancement, external-feature
