### ISSUE TITLE
Dragging tabs in VSCode causes Wayfire / VSCode to crash randomly

### ISSUE THREAD

**Issue by jpy794** [WayfireWM/wayfire#1761] opened 2023-03-14 11:03 UTC
**Describe the bug**
Dragging tabs in VSCode sometimes will cause only VSCode itself to crash, sometimes will cause Wayfire to crash.
Dragging works fine in Sway, so I guess there may be something wrong with Wayfire?

**To Reproduce**
1. Launch Code-OSS 1.76.1 with `--enable-features=UseOzonePlatform --ozone-platform=wayland`
2. Drag any tab, e.g. welcome page
3. Try another tab if nothing happened

**Expected behavior**
VSCode and Wayfire don't crash.

**Screenshots or stacktrace**
```
II 14-03-23 16:32:36.830 - [src/view/xdg-shell.cpp:213] new xdg_shell_stable surface: Code - OSS app-id: code-oss
DD 14-03-23 16:32:39.137 - [src/core/seat/pointer.cpp:151] change cursor focus (null) -> 0x562d5da7cc10
II 14-03-23 16:32:51.893 - [wayland] error in client communication (pid 22799)
DD 14-03-23 16:32:51.895 - [src/core/seat/pointer.cpp:151] change cursor focus 0x562d5da7cc10 -> (null)
DD 14-03-23 16:32:51.924 - [src/core/seat/pointer.cpp:151] change cursor focus 0x562d5da7cc10 -> (null)
EE 14-03-23 16:32:51.924 - [src/main.cpp:134] Fatal error: Segmentation fault
EE 14-03-23 16:32:51.936 - #1  wf::print_trace(bool) ??:?
EE 14-03-23 16:32:51.944 - #2  __sigaction ??:?
EE 14-03-23 16:32:51.955 - #3  wf::pointer_t::force_release_buttons() ??:?
EE 14-03-23 16:32:51.966 - #4  wf::pointer_t::update_cursor_focus(std::shared_ptr<wf::scene::node_t>) ??:?
EE 14-03-23 16:32:51.977 - #5  wf::pointer_t::update_cursor_position(long, bool) ??:?
EE 14-03-23 16:32:51.987 - #6  wf::pointer_t::handle_pointer_axis(wlr_pointer_axis_event*, wf::input_event_processing_mode_t) ??:?
EE 14-03-23 16:32:51.998 - #7  std::_Function_handler<void (wf::signal::connection_base_t*&), wf::signal::provider_t::emit<wf::scene::root_node_update_signal>(wf::scene::root_node_update_signal*)::{lambda(wf::signal::connection_base_t*)#1}>::_M_invoke(std::_Any_data const&, wf::signal::connection_base_t*&) ??:?
EE 14-03-23 16:32:52.009 - #8  wf::output_layout_t::get_current_configuration() ??:?
EE 14-03-23 16:32:52.020 - #9  wf::scene::update(std::shared_ptr<wf::scene::node_t>, unsigned int) ??:?
EE 14-03-23 16:32:52.032 - #10 wf::scene::update(std::shared_ptr<wf::scene::node_t>, unsigned int) ??:?
EE 14-03-23 16:32:52.042 - #11 wf::scene::update(std::shared_ptr<wf::scene::node_t>, unsigned int) ??:?
EE 14-03-23 16:32:52.053 - #12 wf::scene::update(std::shared_ptr<wf::scene::node_t>, unsigned int) ??:?
EE 14-03-23 16:32:52.064 - #13 wf::scene::update(std::shared_ptr<wf::scene::node_t>, unsigned int) ??:?
EE 14-03-23 16:32:52.075 - #14 wf::scene::update(std::shared_ptr<wf::scene::node_t>, unsigned int) ??:?
EE 14-03-23 16:32:52.087 - #15 wf::scene::update(std::shared_ptr<wf::scene::node_t>, unsigned int) ??:?
EE 14-03-23 16:32:52.097 - #16 wf::scene::update(std::shared_ptr<wf::scene::node_t>, unsigned int) ??:?
EE 14-03-23 16:32:52.109 - #17 wf::wlr_view_t::unmap() ??:?
EE 14-03-23 16:32:52.120 - #18 _start ??:?
EE 14-03-23 16:32:52.128 - #19 wl_signal_emit_mutable ??:?
EE 14-03-23 16:32:52.137 - #20 wlr_cursor_create ??:?
EE 14-03-23 16:32:52.146 - #21 wlr_cursor_create ??:?
EE 14-03-23 16:32:52.155 - #22 wlr_xdg_popup_destroy ??:?
EE 14-03-23 16:32:52.164 - #23 wlr_surface_destroy_role_object ??:?
EE 14-03-23 16:32:52.173 - #24 wlr_surface_destroy_role_object ??:?
EE 14-03-23 16:32:52.181 - #25 wl_resource_queue_event ??:?
EE 14-03-23 16:32:52.189 - #26 wl_client_destroy ??:?
EE 14-03-23 16:32:52.198 - #27 wl_array_add ??:?
EE 14-03-23 16:32:52.206 - #28 wl_event_loop_dispatch ??:?
EE 14-03-23 16:32:52.215 - #29 wl_display_run ??:?
EE 14-03-23 16:32:52.226 - #30 main ??:?
EE 14-03-23 16:32:52.234 - #31 __libc_init_first ??:?
EE 14-03-23 16:32:52.243 - #32 __libc_start_main ??:?
EE 14-03-23 16:32:52.253 - #33 _start ??:?
```

**Wayfire version**
wayfire-git 0.7.5.r509.g4dd373d2-1

**Comment by soreau** [comment] 2023-03-14 11:27
I was able to reproduce this by running `mousepad` twice to bring up two tabs, then try to drag a tab off to create a new window.

**Comment by ammen99** [comment] 2023-08-20 14:18
I cannot reproduce with latest master + #1857, can someone else confirm this?

**Comment by ssfdust** [comment] 2023-08-21 03:08
@ammen99 Yes, I can confirm. In fact, the issue may be resolved after trx pr merged.

**Closed** 2023-08-23 06:16 UTC
Labels: bug
