### ISSUE TITLE
Raise focus on mouse follow

### ISSUE THREAD

**Issue by alexherbo2** [WayfireWM/wayfire#592] opened 2020-07-15 20:25 UTC

**Comment by soreau** [comment] 2020-07-15 20:32
Fixing up wayfire-plugins-extra #17 would provide this feature.

**Comment by ammen99** [comment] 2020-07-16 05:52
Duplicate of https://github.com/WayfireWM/wayfire-plugins-extra/issues/16

**Closed by ammen99** 2020-07-16 05:52 UTC
