### ISSUE TITLE
remove dependency on deprecated wlroots noop backend

### ISSUE THREAD

**Issue by XGIVolari** [WayfireWM/wayfire#1377] opened 2021-12-08 12:08 UTC
**Describe the bug**
Currently, wayfire cannot be built against the master branch of wlroots. This is because the latter has [completely removed the noop backend two weeks ago,](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/1d3dd7fc08f22f2e82cb812ced822369e984d845) which wayfire still expects to be present.

**To reproduce**
Build master branch of wayfire against master branch of wlroots.

**Expected behavior**
The build should finish successfully.

**Relevant log snippet**
```
In file included from ../wayfire-9999/src/region.cpp:2:
../wayfire-9999/src/api/wayfire/nonstd/wlroots-full.hpp:85:10: fatal error: wlr/backend/noop.h: No such file or directory
   85 | #include <wlr/backend/noop.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by ammen99** [comment] 2021-12-08 12:46
Thanks for the report, this is a duplicate of #1351

**Closed by ammen99** 2021-12-08 12:46 UTC
Labels: bug
