### ISSUE TITLE
wm-actions/toggle_sticky crash

### ISSUE THREAD

**Issue by aalhitennf** [WayfireWM/wayfire#1267] opened 2021-08-23 19:09 UTC
**Describe the bug**
Wayfire sometimes crashes when pressing toggle_sticky keybind

**To Reproduce**
1. Enable plugin wm_actions
2. Bind key to toggle
    [wm-actions]
    toggle_sticky = <super> KEY_S
3. Wayfire occasionally crashes

**Screenshots or stacktrace**
EE 23-08-21 21:27:03.888 - [wayfire-0.7.2/src/main.cpp:141] Fatal error: Segmentation fault
(EE) failed to write to XWayland fd: Broken pipe

**Wayfire version**
0.7.2 from aur

**Comment by ammen99** [comment] 2024-03-08 13:06
Has this happened with recent Wayfire versions (if you're still using Wayfire)?

**Comment by aalhitennf** [comment] 2024-03-09 04:03
I haven't used Wayfire for a long time so no idea 🤷‍♂️

**Comment by ammen99** [comment] 2024-03-09 07:31
Well then I'd close the issue because I cannot reproduce:) Thanks for your reply.

**Closed by ammen99** 2024-03-09 07:31 UTC
Labels: bug, needs information
