### ISSUE TITLE
Ability to load XKB files

### ISSUE THREAD

**Issue by alexherbo2** [WayfireWM/wayfire#872] opened 2020-11-15 17:47 UTC
In Sway, we can do:

``` sh
swaymsg input type:keyboard xkb_file /path/to/qwerty-lafayette.xkb
```

https://github.com/fabi1cazenave/qwerty-lafayette

**Comment by ammen99** [comment] 2020-11-15 17:53
Duplicate of #403 :)

**Closed by ammen99** 2020-11-15 17:53 UTC
Labels: enhancement

**Comment by alexherbo2** [comment] 2020-11-15 19:24
3 duplicates by me xd

@ammen99 sorry
