### ISSUE TITLE
Flatpak apps doesn't apply the system font and cursor theme on wayfire

### ISSUE THREAD

**Issue by bluebyt** [WayfireWM/wayfire#2082] opened 2023-12-28 13:56 UTC
**Describe the bug**
Flatpak apps doesn't apply the system font and my cursor theme on wayfire, it's working on Gnome and Hyprland.

**To Reproduce**
1. Install a flatpak app ex: [Prompt](https://blogs.gnome.org/chergert/2023/12/14/prompt/)
2. Mouse over the flatpak app the cursor change to the default Adwaita and the default font theme   

**Expected behavior**
Fplatpak should follow the cursor and font theme

**Screenshots**
![ex](https://github.com/WayfireWM/wayfire/assets/18442224/a803e8aa-0ac1-47ee-895a-9eee3e2cdc0f)

[Video](https://streamable.com/0qcnqe)

**Wayfire version**
0.9.0-b5c0a0b4 (Dec 23 2023, branch 'HEAD')

[wayfire.ini](https://pastebin.com/tQRYtqzy)
[env variable](https://pastebin.com/yme7TdPw)

Update:
When I open a flatpak app with the terminal, I get an error with the portal:
Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop

**Comment by ammen99** [comment] 2024-02-05 11:05
You probably need to configure which portals to be used in Wayfire. Wayfire by itself has absolutely nothing to do with fonts, so I suppose this is a duplicate of #1995 - that issue should have some info on how to configure Wayfire for newer xdg-desktop-portal versions until we have a solution upstream.

**Closed by ammen99** 2024-02-05 11:05 UTC
Labels: bug

**Comment by bluebyt** [comment] 2024-02-05 15:37
Ok, I will check if my environment variables and portals are set correctly, this is the way I started the portals in the autostart of wayfire.ini, maybe some variable are missing. 

[autostart]
0_0 = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
portal = sleep 1 && (XDG_SESSION_TYPE=wayland XDG_CURRENT_DESKTOP=sway /usr/lib/xdg-desktop-portal --replace & /usr/lib/xdg-desktop-portal-wlr)

**Comment by ammen99** [comment] 2024-02-05 15:38
This looks good if you use the older portal versions but I'm not sure whether you don't need a special file for newer portal versions (>= 1.17)
