### ISSUE TITLE
Idle pluggin

### ISSUE THREAD

**Issue by limbo127** [WayfireWM/wayfire#1668] opened 2022-12-29 15:51 UTC
Hello, 
idle plugin 
- with two monitor, when idle detect, two monitor dpms is off , but when keyboard/mouse is activated, only one monitor dpms on
- is it possible to not idle when sound card or video is starting ?

Regards, 
Nicolas

**Comment by ammen99** [comment] 2024-03-08 12:22
Hi, a long time has passed, have you tried newer Wayfire versions, does the DPMS problem still happen? If yes and you'd like to see this issue resolved, please redirect Wayfire's output to a log and upload it so that we can see what is going on, I expect some wlroots errors.

**Comment by ammen99** [comment] 2024-03-08 12:58
Actually seems like a duplicate of #1366

**Closed by ammen99** 2024-03-08 12:58 UTC
Labels: bug, needs information
