### ISSUE TITLE
Qt menus can go out of screen

### ISSUE THREAD

**Issue by tsujan** [WayfireWM/wayfire#1129] opened 2021-03-24 04:30 UTC
**Describe the bug**
Parts of a Qt menu can be offscreen, depending on where it's opened.

**To Reproduce**
1. Put a Qt app that has context menu near the screen bottom.
2. Right click to open its context menu.

Then, the bottom part of the context menu might go offscreen.

**Expected behavior**
Menus shouldn't go offscreen, as they don't in Plasma-Wayland: when a context menu is opened near the screen bottom, its top left corner shouldn't be positioned at the cursor's position.

GTK menus didn't have this problem as far as I tested.

**Wayfire version**
Latest git, up to this moment.

**Comment by unrelentingtech** [comment] 2021-03-24 16:23
Qt currently does not set constraint adjustment at all, so the compositor is not supposed to do any adjustment:

https://bugreports.qt.io/browse/QTBUG-87303

I am curious how Plasma manages to do it anyway.

**Comment by ammen99** [comment] 2021-06-16 08:41
Closing this since it is a Qt issue and we can't really do much about it.

If the default constraint adjustment is wrong, then it is wrong in wlroots (it is responsible for this) and you should open a bug there. However, since the Qt issue remains open, I suppose that the issue is indeed in Qt.

**Closed by ammen99** 2021-06-16 08:41 UTC
Labels: bug

**Comment by escape0707** [comment] 2021-09-16 00:07
I'm experiencing the same problem with Telegram, qBittorrent on GNOME Wayland. 

Telegram dev says maybe it's because GNOME fakes window position. 

I'm not experienced with DE and Qt development so would you guys give a look and leave your opinions?

https://github.com/telegramdesktop/tdesktop/issues/16943

The bug reported in Qt tracker has a level 2 importance but is still not confirm yet, which is sad. 🙁

**Comment by unrelentingtech** [comment] 2021-09-16 11:20
Just responded in that thread, but copying here: I have found what KDE does, it indeed just always doesn't let popups go off-screen.

https://github.com/KDE/kwin/commit/8ef363cc210b12bba87bba78160ed55b9725e08d#diff-5425403b99ccea8dfc05a698d2ec3d51b684467a1bdd84a861df72caf4fe1acdR503-R508

```c++
    // Potentially a client could set no constraint adjustments
    // and we'll be offscreen.

    // The spec implies we should place window the offscreen. However,
    // practically Qt doesn't set any constraint adjustments yet so we can't.
    // Also kwin generally doesn't let clients do what they want
```

I… guess there is some logic to this (who ever *wants* the off-screen behavior?) but how about toolkits conform to the spec ;)
