### ISSUE TITLE
Chromium File-Dialog Segfault Wayfire

### ISSUE THREAD

**Issue by solunix** [WayfireWM/wayfire#2100] opened 2024-01-17 18:37 UTC
**Describe the bug**
File-Open Dialog Crtl-O or from an upload Link, causes Wayfire to crash.

**To Reproduce**
1. Open Chromium
2. Press Ctrl-O or surf to site where you can upload something
3. Wayfire closes with a Segmentation fault

**Expected behavior**
Wayfire stays stable and the Chromium File-Dialog appears.

**Screenshots or stacktrace**
Starting wayfire with Debug Switch give this output:
II 17-01-24 19:20:34.347 - [wayfire-0.8.0/src/view/xdg-shell/xdg-toplevel-view.cpp:29] new xdg_shell_stable surface: Datei öffnen app-id: chromium
II 17-01-24 19:20:34.421 - [wayfire-0.8.0/plugins/tile/tree.cpp:338] We store data??
WW 17-01-24 19:20:34.422 - [wayfire-0.8.0/src/output/workspace-impl.cpp:399] Removing view view id=51 title="Datei öffnen" app_id="chromium" from wset id=1 but the view is not there!
EE 17-01-24 19:20:34.522 - [wayfire-0.8.0/src/main.cpp:134] Fatal error: Segmentation fault
EE 17-01-24 19:20:34.551 - #1  wf::print_trace(bool) ??:?
EE 17-01-24 19:20:34.574 - #2  __sigaction ??:?
EE 17-01-24 19:20:34.602 - #3  wf::workspace_set_t::get_current_workspace() ??:?
EE 17-01-24 19:20:34.624 - #4  wf::tile::get_wset_local_coordinates(std::shared_ptr<wf::workspace_set_t>, wf::point_t) ??:?
EE 17-01-24 19:20:34.646 - #5  wf::tile::get_wset_local_coordinates(std::shared_ptr<wf::workspace_set_t>, wlr_box) ??:?
EE 17-01-24 19:20:34.668 - #6  wf::tile::view_node_t::calculate_target_geometry() ??:?
EE 17-01-24 19:20:34.691 - #7  wf::tile::view_node_t::update_transformer() ??:?
EE 17-01-24 19:20:34.719 - #8  std::_Function_handler<void (wf::signal::connection_base_t*&), wf::signal::provider_t::emit<wf::view_geometry_changed_signal>(wf::view_geometry_changed_signal*)::{lambda(wf::signal::connection_base_t*)#1}>::_M_invoke(std::_Any_data const&, wf::signal::connection_base_t*&) ??:?
EE 17-01-24 19:20:34.747 - #9  wf::wl_timer<true>::is_connected() ??:?
EE 17-01-24 19:20:34.774 - #10 wf::view_implementation::emit_geometry_changed_signal(nonstd::observer_ptr<wf::toplevel_view_interface_t>, wlr_box) ??:?
EE 17-01-24 19:20:34.801 - #11 wf::view_implementation::emit_toplevel_state_change_signals(nonstd::observer_ptr<wf::toplevel_view_interface_t>, wf::toplevel_state_t const&) ??:?
EE 17-01-24 19:20:34.829 - #12 wf::xdg_toplevel_view_t::handle_toplevel_state_changed(wf::toplevel_state_t) ??:?
EE 17-01-24 19:20:34.856 - #13 wf::xdg_toplevel_view_t::handle_toplevel_state_changed(wf::toplevel_state_t) ??:?
EE 17-01-24 19:20:34.884 - #14 std::_Function_handler<void (wf::signal::connection_base_t*&), wf::signal::provider_t::emit<wf::xdg_toplevel_applied_state_signal>(wf::xdg_toplevel_applied_state_signal*)::{lambda(wf::signal::connection_base_t*)#1}>::_M_invoke(std::_Any_data const&, wf::signal::connection_base_t*&) ??:?
EE 17-01-24 19:20:34.912 - #15 wf::wl_timer<true>::is_connected() ??:?
EE 17-01-24 19:20:34.941 - #16 wf::xdg_toplevel_t::apply() ??:?
EE 17-01-24 19:20:34.969 - #17 wf::txn::transaction_t::apply(bool) ??:?
EE 17-01-24 19:20:34.997 - #18 std::_Function_handler<void (wf::signal::connection_base_t*&), wf::signal::provider_t::emit<wf::view_fullscreen_request_signal>(wf::view_fullscreen_request_signal*)::{lambda(wf::signal::connection_base_t*)#1}>::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation) ??:?
EE 17-01-24 19:20:35.019 - #19 wl_event_loop_dispatch ??:?
EE 17-01-24 19:20:35.043 - #20 wl_display_run ??:?
EE 17-01-24 19:20:35.071 - #21 main ??:?
EE 17-01-24 19:20:35.094 - #22 __libc_init_first ??:?
EE 17-01-24 19:20:35.115 - #23 __libc_start_main ??:?
EE 17-01-24 19:20:35.142 - #24 _start ??:?
(EE) failed to read Wayland events: Broken pipe

**Wayfire version**
0.8.0 at Garuda Arch-Linux 
Chromium Version 120.0.6099.224 (Offizieller Build) Arch Linux (64-Bit)

**Comment by ammen99** [comment] 2024-02-14 14:03
Looking at the backtrace, I believe this is a duplicate of #2078, a fix is coming very soon: #2140

**Closed by ammen99** 2024-02-14 14:03 UTC
Labels: bug
