### ISSUE TITLE
Corner bug in Waybar

### ISSUE THREAD

**Issue by 0xarch** [WayfireWM/wayfire#2149] opened 2024-02-19 06:24 UTC
**Describe the bug**
set style `border-radius` for waybar then
the corner will be filled by window above

enabled plugins: [ ... default plugins, [winshadows](https://github.com/timgott/wayfire-shadows) ]

**To Reproduce**
```css
window#waybar{
  border-radius: 25px 25px 0 0;
}
```

**Expected behavior**
Clean corner , like in Sway

**Screenshots or stacktrace**
Wayfire:
![图片](https://github.com/WayfireWM/wayfire/assets/89088411/57488103-9e80-4116-83e5-0c4fa9dc97ea)
Sway:
![图片](https://github.com/WayfireWM/wayfire/assets/89088411/5afd7580-b8dd-4b80-a741-134c2b18cc84)

**Wayfire version**
0.9.0-906a3105 (Feb 18 2024) branch master

**Comment by 0xarch** [comment] 2024-02-19 06:32
also filled by invert plugin
won't happen when use alpha plugin on waybar

**Comment by soreau** [comment] 2024-02-19 06:36
Does it help if you try setting the opacity to 0.99 in the css? Sounds like a similar issue to [this one](https://github.com/WayfireWM/wayfire/issues/2125#issuecomment-1932792222).

**Comment by 0xarch** [comment] 2024-02-19 06:46
> Does it help if you try setting the opacity to 0.99 in the css? Sounds like a similar issue to [this one](https://github.com/WayfireWM/wayfire/issues/2125#issuecomment-1932792222).

css `opacity: <number>` has no effect, if `<number>` = 0 waybar will be transparent with the bug all bar area.

opacity: 0.99
![图片](https://github.com/WayfireWM/wayfire/assets/89088411/69a3627b-1e7d-4db4-94d7-7addabdca09e)
opacity 0
![图片](https://github.com/WayfireWM/wayfire/assets/89088411/114fc30c-72ac-4e29-848f-f60551d7f4b7)

**Comment by soreau** [comment] 2024-02-19 07:28
I built latest waybar here and this is what I found:

```
$ WAYLAND_DEBUG=1 waybar -s style.css |& grep -B1 opaque
[3797488.163]  -> wl_region#41.add(0, 0, 1280, 30)
[3797488.166]  -> wl_surface#36.set_opaque_region(wl_region#41)
```

where `style.css` is the one you posted and the compositor resolution is 1280x720. This means that waybar is setting the opaque region incorrectly. Closing this as a duplicate of [#2125](https://github.com/WayfireWM/wayfire/issues/2125).

**Closed by soreau** 2024-02-19 07:28 UTC
Labels: bug
