### ISSUE TITLE
Plugging in dock often doesn't detect monitors

### ISSUE THREAD

**Issue by szbergeron** [WayfireWM/wayfire#567] opened 2020-06-21 17:17 UTC
ix.io/2pNi

Reproducible especially when wayfire was started with dock unplugged and plugging it in the first time

**Comment by ammen99** [comment] 2020-06-21 18:21
This almost seems like an issue with wlroots, have you tried sway?

**Comment by szbergeron** [comment] 2020-06-25 19:52
Hm, seems present there as well

**Comment by ammen99** [comment] 2020-06-25 21:42
Please open a wlroots issue then.

**Comment by szbergeron** [comment] 2020-07-10 20:13
This seems to no longer be reproducible on sway, but does still occur in the same way on wayfire. I'm trying to get a debug build working again so I can post logs, but current is using wlroots 0.10.0.r234.g842df2bd-1.

**Comment by ammen99** [comment] 2020-07-10 20:17
Reopening although I have difficulty seeing what exactly Wayfire is doing wrong ... because wlroots is responsible for detecting the monitors. But who knows, maybe some stale state remains. Anyway, logs should tell us what is going on.

**Comment by AdrianVovk** [comment] 2020-07-10 20:50
Bisect sway to see what fixes it?

**Comment by ammen99** [comment] 2020-08-01 06:34
@szbergeron Yesterday you mentioned on IRC that the problem is now gone IIRC ?

**Comment by szbergeron** [comment] 2020-08-01 11:22
It seems to be, yes, and is a wlroots issue anyway if not fixed

**Comment by ammen99** [comment] 2020-08-01 14:02
Closing then :)

**Closed by ammen99** 2020-08-01 14:02 UTC
