### ISSUE TITLE
Add an input.xkb_file option

### ISSUE THREAD

**Issue by alexherbo2** [WayfireWM/wayfire#418] opened 2020-02-19 20:55 UTC
Similar to [`sway-input(5)`].

[`sway-input(5)`]: https://github.com/swaywm/sway/blob/master/sway/sway-input.5.scd

**Comment by ammen99** [comment] 2020-02-24 19:10
As @epsilon-0 pointed out, this is a duplicate of #403

**Closed by ammen99** 2020-02-24 19:10 UTC
