### ISSUE TITLE
Blurry xwayland with scaling

### ISSUE THREAD

**Issue by Idiot64** [WayfireWM/wayfire#1180] opened 2021-05-14 11:22 UTC
**Describe the bug**
So, x11 apps only have a maximum resolution of 1080p instead of 4k when 2x scaling is activated

**To Reproduce**
1. Have a monitor that has better resolution than 1080p
2. Change scaling in config file
3. x11 apps will only have 1080 as max res

also, if you change anything in the config file, the scaling will reset

**Expected behavior**
x11 apps should be able to use 4k, it doesn't even get displayed in the options of a game menu, they say the maximum res is 1080

**Screenshots or stacktrace**
happens with every x11 app
![image](https://user-images.githubusercontent.com/70104078/118263991-53084d80-b4b7-11eb-9397-b406bb12215e.png)

**Wayfire version**
wayfire 0.7.1-2 (+16 1.84) aur

**Comment by Idiot64** [comment] 2021-05-14 11:22
sorry if this is a duplacite, I haven't seen it anywhere else

**Comment by Idiot64** [comment] 2021-05-14 11:26
also, I'm not sure if this is x11 only but I can't check right now

when i use a lower resolution, than 1080 on x11 apps, the app will become smaller and won't fill the screen anymore

**Comment by ammen99** [comment] 2021-05-14 11:33
This is a general problem, which Wayfire can hardly fix. You should check out #599

**Comment by Idiot64** [comment] 2021-05-14 11:34
alright, some x11 apps fill the screen, weird

**Comment by ammen99** [comment] 2021-06-13 11:46
Closing as duplicate of #599. The Wayfire side of the things is implemented, but we need to have the Xwayland patch merged, otherwise, you have to build custom versions of Xwayland, wlroots and Wayfire.

**Closed by ammen99** 2021-06-13 11:46 UTC
Labels: bug
