### ISSUE TITLE
How to suppress the flickering on the terminal while using wayfire : WLR_DRM_NO_MODIFIERS=1 does not work.

### ISSUE THREAD

**Issue by Marietto2008** [WayfireWM/wayfire#2179] opened 2024-03-05 22:13 UTC
Hello.

This is the startup script that I use when I want to start wayland / wayfire on my system : 
```

#!/usr/local/bin/zsh
env WLR_NO_HARDWARE_CURSORS=1 LIBSEAT_BACKEND=consolekit2 ck-launch-session dbus-run-session wayfire
```

unfortunately with those parameters I see a lot of flickering on the terminal. I read that the flickering can be suppressed adding this parameter :

`WLR_DRM_NO_MODIFIERS=1 `

so,the whole command became :

```
#!/usr/local/bin/zsh
env WLR_DRM_NO_MODIFIERS=1 WLR_NO_HARDWARE_CURSORS=1 LIBSEAT_BACKEND=consolekit2 ck-launch-session dbus-run-session wayfire
```

unfortunately WLR_DRM_NO_MODIFIERS=1 does not work for me. If I add it,the error is : can't start wayland server. 
How to fix this bug ? thanks.

**Comment by Marietto2008** [comment] 2024-03-05 22:32
https://pastebin.ubuntu.com/p/BkfKmDxt2M/

**Comment by soreau** [comment] 2024-03-06 13:09
It looks like the problem is with your drivers:

`EE 05-03-24 23:30:08.401 - [GLES2] GL_INVALID_OPERATION error generated. EGLImage not supported`

**Comment by Marietto2008** [comment] 2024-03-06 13:35
man,it worked until yesterday. I haven't removed or modified the driver. 

[root@marietto-I5 /usr/ports/x11-toolkits/wlroots]==> nvidia-smi
Wed Mar  6 14:34:43 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: N/A      |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1060 3GB    Off |   00000000:01:00.0  On |                  N/A |
| 58%   43C    P8              7W /  120W |     354MiB /   3072MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     18599      G   firefox                                       157MiB |
|    0   N/A  N/A     57858      G   /usr/local/libexec/Xorg                       191MiB |
|    0   N/A  N/A     77339      G   xfwm4                                           2MiB |
+-----------------------------------------------------------------------------------------+

**Comment by Marietto2008** [comment] 2024-03-06 13:42
This is not exact. The driver worked good,until yesterday,without passing the parameter "WLR_DRM_NO_MODIFIERS=1"

**Comment by soreau** [comment] 2024-03-07 19:45
Since you have wayfire working now with your setup, is the flickering still present? If not, we can probably close this issue.

**Comment by Marietto2008** [comment] 2024-03-08 15:35
I'm not sure that this issue can be closed because I see a new error at the moment and I don't know if it is connected to the flickering. I will start a new discussion soon. That error does not prevent wayfire from starting,but it freezes it suddenly from time to time.

**Comment by mrsteve0924** [comment] 2024-03-08 16:16
yea you definitely cannot use WLR_DRM_NO_MODIFIERS=1  and the nvidia proprietary drivers.  
i used nvidia 550 and i didnt have flickering in the terminal.  i did see flickering in programs like vncviewer, teamviewer, virtualbox.  seems like programs that screen share mostly.  so i moved back to using nouveau driver for the time being

**Closed** 2024-03-27 11:56 UTC
Labels: bug
