### ISSUE TITLE
Sticky windows steal focus on workspace switching

### ISSUE THREAD

**Issue by pushqrdx** [WayfireWM/wayfire#927] opened 2020-12-06 22:47 UTC
**Describe the bug**
I use sticky windows in combination with float to pin firefox's picture in picture videos on top of all workspaces, However switching workspaces results in that window regaining focus instead of the last active view. This could be a another manifestation of #861 

**To Reproduce**
1. Enter a pip of any video
2. Toggle float and sticky
3. Switch workspaces

**Expected behavior**
Last workspace active view regaining focus

**Actual behavior**
The pip window steals focus

**Wayfire version**
git

**Comment by ammen99** [comment] 2020-12-07 06:44
Yeah duplicate of #861

**Closed by ammen99** 2020-12-07 06:44 UTC
Labels: bug
