### ISSUE TITLE
sublayer-ed views steal keyboard focus

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#662] opened 2020-08-03 04:39 UTC
I have 2 open window, qtcreator and vlc.
vlc is keep_above and qtcreator is bigger than the vlc window,
vlc sits on top. 
vlc and qtcreator are running with xwayland backend.
in QtCreator I clink in the menubar on file to open file menu and switch to edit submenu
by hovering on edit. 

Expected => Edit Menu
Result => Vlc steals focus

Sometimes you need 2-3 attempts to reproduce that menu closes,
but on each menu/hover/switch vlc takes keyboard focus

**Comment by ammen99** [comment] 2020-09-04 14:40
Actually this is a duplicate of #666

**Closed by ammen99** 2020-09-04 14:40 UTC
