### ISSUE TITLE
Blurring only parts of an application

### ISSUE THREAD

**Issue by bafaleo2** [WayfireWM/wayfire#322] opened 2019-10-19 19:42 UTC
Is there a way I can only blur parts of an application?
In KDE Plasma there is KWindowSystem (which funnily enough doesn't work with Wayland but its a good example) where I can call enableBlurBehind(WId window, bool enable, const QRegion &region) and just give it the id and the region to blur.

**Comment by ammen99** [comment] 2019-10-19 19:47
Duplicate of #158 afaict.

I am not personally interested to support this. One can easily clone the blur plugin and add support though.

**Closed** 2019-10-19 19:48 UTC

**Comment by bafaleo2** [comment] 2019-10-19 19:50
Sorry I should have looked it up properly. I'll try my luck

**Comment by ammen99** [comment] 2019-10-19 19:59
Just to clarify, I can help with answering technical question about development of such a plugin, but not develop it :)
