### ISSUE TITLE
Permission errors when launching Wayfire

### ISSUE THREAD

**Issue by etna** [WayfireWM/wayfire#733] opened 2020-09-11 09:28 UTC
Built Wayfire with the following variables:
`LD_LIBRARY_PATH=/home/etna/Runtime/opt/extra-LO-deps/lib:/home/etna/Runtime/opt/sqlite-3.31.1/lib:/home/etna/Runtime/opt/libbz2-1.0.8/lib:/home/etna/Runtime/opt/Python3.8.2/lib:/home/etna/Runtime/opt/Python3.8.2/lib64:/home/etna/Runtime/opt/libssh2-1.9.0/lib:/home/etna/Runtime/opt/libnotify-0.7.8/lib:/home/etna/Runtime/opt/libnotify-0.7.8/lib/x86_64-linux-gnu:/home/etna/Runtime/opt/lib:/home/etna/Runtime/lib:/home/etna/Runtime/lib/x86_64-linux-gnu:/home/etna/Runtime/lib64:$LD_LIBRARY_PATH PATH=/home/etna/Runtime/opt/sqlite-3.31.1/bin:/home/etna/Runtime/opt/libbz2-1.0.8/bin:/home/etna/Runtime/opt/Python3.8.2/bin:/home/etna/Runtime/opt/libnotify-0.7.8/bin:/home/etna/Runtime/opt/gperf-3.1/bin:/home/etna/Runtime/bin:/home/etna/RUnlibe:$PATH PKG_CONFIG_PATH=/home/etna/Runtime/opt/libxml2-2.9.10/lib/pkgconfig:/home/etna/Runtime/Applications/Wayfire/lib/pkgconfig:/home/etna/Runtime/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH meson -Dprefix=/home/etna/Runtime/Applications/Wayfire -Duse_system_wfconfig=disabled -Duse_system_wlroots=disabled build`

Build was successful and I have an installation in /home/etna/Runtime/Applications/Wayfire. But when I try to launch it, I get the following error:
```
II 11-09-20 17:19:03.403 - [src/main.cpp:260] Starting wayfire
EE 11-09-20 17:19:03.403 - [backend/session/direct-ipc.c:47] Do not have root privileges; cannot become DRM master
EE 11-09-20 17:19:03.404 - [backend/session/session.c:96] Failed to load session backend
EE 11-09-20 17:19:03.404 - [backend/backend.c:286] Failed to start a DRM session
EE 11-09-20 17:19:03.404 - [src/main.cpp:204] Fatal error: Segmentation fault
EE 11-09-20 17:19:03.518 - #1  signal_handler(int) ../src/main.cpp:206
EE 11-09-20 17:19:03.551 - #2  killpg ??:?
EE 11-09-20 17:19:03.593 - #3  wlr_backend_get_renderer ../subprojects/wlroots/backend/backend.c:54
EE 11-09-20 17:19:03.707 - #4  main ../src/main.cpp:272 (discriminator 1)
EE 11-09-20 17:19:03.740 - #5  __libc_start_main ??:?
EE 11-09-20 17:19:03.866 - #6  _start ??:?
```

Changing Wayfire's owner to root:root had no results. Neither did chmod a+s. What am I doing wrong here?

**Comment by ammen99** [comment] 2020-09-11 11:47
Do you have systemd or elogind? Seems like wlroots was built without support.

**Comment by etna** [comment] 2020-09-11 13:53
> Do you have systemd or elogind? Seems like wlroots was built without support for neither of them.

I have, but I did not install the development packages because I didn't want to use them. Instead, I added `export WLR_SESSION=direct` to the TTY before launching Wayfire, with the same results.

**Comment by myfreeweb** [comment] 2020-09-11 14:06
Could that path be on a `nosuid` mount?

**Comment by etna** [comment] 2020-09-11 14:14
> Could that path be on a `nosuid` mount?

I'm not sure, and I'm also not really familiar with the concept of `setuid`, but I'm quite certain my filesystem is not mounted with `nosuid`.

**Comment by ammen99** [comment] 2020-09-11 14:34
On my system, I just need `chmod a+s /bin/wayfire` and `chown root:root /bin/wayfire`. You said you tried to change both, but did you change both at the same time?

**Comment by etna** [comment] 2020-09-11 14:45
> On my system, I just need `chmod a+s /bin/wayfire` and `chown root:root /bin/wayfire`. You said you tried to change both, but did you change both at the same time?

Not at the same time. First I tried `chown root:root $HOME/Runtime/Applications/Wayfire/bin/wayfire`, but it didn't work, so i reverted it to the original ownership and did `chmod a+s $HOME/Runtime/Applications/Wayfire/bin/wayfire`, with the same results.

**Comment by ammen99** [comment] 2020-09-11 14:48
You definitely need both. SUID means to run as the owner of the file. If the owner is your user, then SUID has no effect.

**Comment by etna** [comment] 2020-09-11 14:53
> You definitely need both. SUID means to run as the owner of the file. If the owner is your user, then SUID has no effect.

I built it as a user (i.e.: without sudo or root). So I should do both `chown root:root` and `chmod a+s` ?

**Comment by etna** [comment] 2020-09-11 15:09
> Yes, exactly. No matter how you build it, if you start from a tty without systemd/elogind, you need root access (limitation of the kernel/drivers).

That's going to be problematic because setuid ignores the libraries in $HOME/Runtime/{lib,lib64} and $HOME/Runtime/Applications/Wayfire/lib. I will have to copy them out into /usr/lib

**Comment by ammen99** [comment] 2020-09-11 15:14
I do not know of any way to workaround this, LD_LIBRARY_PATH is ignored for SUID for security reasons.

I think there may be some linker flags which force the linker to hardcode the path to all used libraries, however, that may then require recompiling other libraries.

**Comment by ammen99** [comment] 2020-09-19 19:43
Closing as this is not a bug.

**Closed by ammen99** 2020-09-19 19:43 UTC
Labels: invalid
