### ISSUE TITLE
master: empty window frame launching from gtk terminal here...

### ISSUE THREAD

**Issue by CaptainBloodz** [WayfireWM/wayfire#703] opened 2020-08-23 16:36 UTC
Not sure whether distro settings related, or internal...

[empty-wayfire-frame-in-gtk-terminal.zip](https://github.com/WayfireWM/wayfire/files/5114317/empty-wayfire-frame-in-gtk-terminal.zip)

Thks 4 ur attention, interest & support.

**Comment by ammen99** [comment] 2020-08-27 12:49
A screenshot would also be helpful, I also don't understand what the issue is.

**Comment by dkondor** [comment] 2020-08-29 08:05
This might be a duplicate of #494 + I remember seeing another issue with this that I cannot find now.
In the attached screenshot, wayfire is the "wlroots - X11-1" window.
This reliably happens every time when starting wayfire nested in X11. Activating the expo plugin (pressing super) fixes it and then everything works normally.
![empty_window](https://user-images.githubusercontent.com/6224679/91632046-bf6a1c00-ea10-11ea-85f2-d288abba4984.png)
I'm on Ubuntu 18.04 with Intel GPU.

**Comment by ammen99** [comment] 2020-08-29 09:20
Is it possible that https://github.com/WayfireWM/wayfire/pull/689/commits/d00579040ad9d774afb7856442edc37d6152c467 fixes this thing as well?

**Comment by dkondor** [comment] 2020-08-29 10:21
> Is it possible that [d005790](https://github.com/WayfireWM/wayfire/commit/d00579040ad9d774afb7856442edc37d6152c467) fixes this thing as well?

Yes, it fixes it for me!

**Closed** 2020-08-31 09:00 UTC

**Comment by CaptainBloodz** [comment] 2020-08-31 14:50
Master rebuild fixed here too...
Thks 4 ur attention, interest & support.
