### ISSUE TITLE
Set window properties :: set below

### ISSUE THREAD

**Issue by Cognomines** [WayfireWM/wayfire#1302] opened 2021-10-09 16:30 UTC
I want to run an application above the background layer but below all other windows.
https://github.com/spheras/desktopfolder 

when I launch 
`$com.github.spheras.desktopfolder` 
it puts itself above my terminal application. 
I wish this application would paint itself below all windows except the wayland desktop background. 
Is there any way to set a window property such that it stays below other windows? 

Maybe I should ask to the application maintainer.

**Comment by soreau** [comment] 2021-10-09 16:39
I think the background-view plugin can do what you want. You supply it a command to run and an app-id to match, and it should place the surface in the layer you want.

**Comment by ammen99** [comment] 2024-02-26 18:32
Seems like a duplicate of #975

**Closed by ammen99** 2024-02-26 18:32 UTC
Labels: enhancement
