### ISSUE TITLE
wlroots 0.6.0 released

### ISSUE THREAD

**Issue by tjg1** [WayfireWM/wayfire#232] opened 2019-06-05 18:23 UTC
Could you tag a release that compiles with wlroots 0.6.0, so distributions can package it without breaking wayfire? Thanks.

**Comment by ammen99** [comment] 2019-06-05 20:00
Yeah, I want to merge stabilize-api-v2 first, because it has many bug fixes. I'll tag afterwards.

**Comment by CameronNemo** [comment] 2019-06-23 19:22
Said PR has been merged. any word on a release?

**Comment by ammen99** [comment] 2019-06-23 19:51
Sadly there has been a rather serious regression: https://github.com/WayfireWM/wayfire/issues/245
But yeah we're almost ready for a release now.

**Comment by ammen99** [comment] 2019-06-24 14:10
The said bug was fixed, here you go: https://github.com/WayfireWM/wayfire/releases/tag/v0.2

**Closed by ammen99** 2019-06-24 14:10 UTC
