### ISSUE TITLE
With decoration, foot (terminal) is not clipped correctly until first resize

### ISSUE THREAD

**Issue by mntmn** [WayfireWM/wayfire#1809] opened 2023-06-16 19:29 UTC
**Describe the bug**

With decoration plugin enabled, foot (the terminal application) is not clipped correctly, i.e. the application surface overlaps the right and bottom decoration. If I resize the window in any direction, it jerks into place, but it can leave a trail of un-damaged paint artifacts.

Foot: https://codeberg.org/dnkl/foot

**To Reproduce**
1. Enable plugin `decoration`
2. Start `foot`

**Expected behavior**
The application content should be clipped correctly on application startup.

**Screenshots or stacktrace**
Screenshot: http://dump.mntmn.com/screenshot-2023-06-16-20-34-56.png

**Wayfire version**
git master

**Comment by mntmn** [comment] 2023-06-16 20:46
Moreover, when dragging from the top resize handle, it leaves a trail. Screenshot / Photo: https://chat.mnt.re/files/qsajkxbxsibp3fgrg57rackdwe/public?h=-Ai3eyZtMWhQmEf7UAdt8dGPzADKrlW3WifqnzsQF1A

It wasn't actually possible to make a screenshot while resizing a window, so the above is a mobile phone photo.

**Comment by mntmn** [comment] 2023-06-19 20:15
This also happens with `pavucontrol`, which is a GTK3 app.

**Comment by mntmn** [comment] 2023-06-20 09:48
I was thinking about this wrong. There's nothing to clip... I think the decoration just renders at a too small initial width+height, perhaps not considering its own dimensions?

**Comment by mark-herbert42** [comment] 2023-06-23 12:51
This will be fixed with 1704 merged.  I've merged it manually and it is ok there, but the new issue appears - maximize works incorrectly. The issue there is also known -I've commented in 1704 thread.

**Comment by ammen99** [comment] 2023-07-30 14:16
I cannot reproduce on latest master, and since this has been confirmed fixed on another setup, I'm closing the issue. Feel free to reopen if there is still an issue @mntmn

**Closed by ammen99** 2023-07-30 14:16 UTC
Labels: bug

**Comment by mntmn** [comment] 2023-09-01 17:48
@ammen99 sorry for my absence, I can confirm that this is solved now.
