### ISSUE TITLE
Unable to swtch tty after enabling screenlock.

### ISSUE THREAD

**Issue by marcusbritanicus** [WayfireWM/wayfire#1198] opened 2021-05-24 17:04 UTC
**Describe the bug**
On wayfire, after screen lock is enabled, we cannot change the tty. I have tested this using swaylock and my own implementation of screen locking app. The problem seems to be the implementation of `wlr-input-inhibitor-unstable-v1` in the compositor. I think the key presses are exclusively being sent to the app that calls the input-inhibitor without filtering without filtering important key combos like `[Ctrl]-[Alt]-[FN#]`

**To Reproduce**
1. Start wayfire
2. Run swaylock
3. Press `[Ctrl]+[Alt]+[FN#]` to switch to tty `#`

**Expected behavior**
Switch to tty `#`

**Wayfire version**
git

**Comment by ammen99** [comment] 2021-05-24 18:23
Duplicate of #1166

**Closed by ammen99** 2021-05-24 18:23 UTC
Labels: bug
