### ISSUE TITLE
quarter tiling bad unmaximize

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#625] opened 2020-07-25 09:06 UTC
If a view is quarter tiled and the application is un-tiled/maximized from the window buttons the position is weird:
https://drive.google.com/file/d/1M2tzuTaiVvhlnwUrmiBkXt9xFT1GMIEJ/view?usp=sharing

**Comment by ammen99** [comment] 2020-07-26 06:25
I can see what is causing this, this is also something @soreau reported on IRC awhile ago, although the reproduction steps are different (his reproduction steps were moving a view from one output to the other).

Basically, the view is restored to the last geometry it had before tiling. In your video you can see that the view was offscreen right before it was tiled, so it is restored there. Grid should probably clamp the restored geometry to the workarea so the view is always visible, and it should probably try to adjust the view to be around the mouse pointer.

**Comment by ammen99** [comment] 2020-08-07 12:29
This is actually more or less a duplicate of #606

**Closed** 2020-08-07 12:29 UTC
