### ISSUE TITLE
Allow binding touchpad gestures to direct key strokes / combos

### ISSUE THREAD

**Issue by jumpinggoofballs** [WayfireWM/wayfire#452] opened 2020-03-28 16:14 UTC
Example:

`bindkey <ctrl> KEY_TAB = swipe right 3`

Use case: allow manipulating windows or anything else about the environment for which we already have keyboard shortcuts. Most obvious uses for this is switching tabs and going backwards and forwards in browsers. 

This would be a killer feature if we did not have to use `xdotools` / `ydotools` like in other WMs / desktops.

**Comment by myfreeweb** [comment] 2020-03-31 14:03
> going backwards and forwards in browsers

Browsers should implement that natively, with proper feedback/animation (like you're dragging the page with your fingers to reveal the previous page — Safari on macOS had that since forever) :P Gestures that trigger instant jarring actions are IMO not worth it at all.

If this gets implemented, please make sure it only intercepts configured gestures and does not limit the gestures apps get when nothing is configured.

**Comment by jumpinggoofballs** [comment] 2020-03-31 14:20
> If this gets implemented, please make sure it only intercepts configured gestures and does not limit the gestures apps get when nothing is configured.

Of course, this should work like keyboad shortcuts work normally. If the WM has a particular shortcut configured, it captures it. Otherwise it passes it down to the selected window to deal with it.

Also, the way this is done with things like `libinput-gestures` is that there is a threshold of x many pixels before a gesture is judged as intentional, and applied. 

For design, the ideal implementation would look something like this: https://github.com/natask/gestures

And the reason why it would be ideal if this were implemented at the WM level (perhaps as a plugin), is for integration and for portability. Waiting for browsers to intergrated with libinput for stuff like this is impractical. Climate change will kill the children of my unbord children before that happens. And switching tabs with <ctrl> TAB is not only for browsers. That keyboard shortcut is fairly ubiquitous among desktop applications.

**Comment by ammen99** [comment] 2020-03-31 20:08
I have misunderstood what the issue is for. There is nothing preventing a plugin from doing this, but I think it does not belong to the core plugins, so I am closing the issue.

If you or somebody else wants to write a plugin, feel free to reach on #wayfire so that I can give you directions where to start.

**Closed by ammen99** 2020-03-31 20:08 UTC
