### ISSUE TITLE
Sometimes expo plugins fail to switch to the workspace clicked by the mouse.

### ISSUE THREAD

**Issue by xiaohuirong** [WayfireWM/wayfire#2074] opened 2023-12-20 11:20 UTC
**Describe the bug**
Clicking on the workspace you want to switch to when the expo plugin animation has just ended will fall back to the current workspace.

**Expected behavior**
Able to switch correctly to the workspace clicked by the mouse.

**Video**
https://drive.google.com/file/d/1PXhNelTAb5alix3HdREiisN7247rwYGv/view?usp=drive_link
In this video, I want to switch from the 4th workspace to the 5th workspace, eventually falling back to the 4th workspace.
To make it easier to reproduce this issue, you can set a longer animation duration.

**Wayfire version**
wayfire-0.8.0.r53.ge2efa57e built from commit e2efa57e

**Comment by ammen99** [comment] 2023-12-20 11:55
Expo currently explicitly disables handling of clicks during the animation, because we'd need some more code to correctly be able to map input coordinates to the proper workspace.

**Comment by xiaohuirong** [comment] 2023-12-20 12:03
Indeed, Expo does not support interrupting animations with mouse clicks. However, at the moment the animation ends, the Expo plugin exhibits incorrect behavior. My expectation is that the Expo plugin should, at the very least, not respond to clicks at the instant of animation completion, rather than erroneously switching back to the previous workspace.

**Comment by ammen99** [comment] 2024-03-08 11:47
Actually seems like a duplicate of #1863

**Closed by ammen99** 2024-03-08 11:47 UTC
Labels: bug
