### ISSUE TITLE
Hardware cursor is broken after mesa upgrade to 24.2.0 from 24.1.6

### ISSUE THREAD

**Issue by xiaohuirong** [WayfireWM/wayfire#2492] opened 2024-10-09 13:18 UTC
**Describe the bug**
My graphics card is an AMD RX580. After upgrading Mesa from version 24.1.6 to 24.2.0, the hardware cursor broke, and Wayfire started using the software cursor.

**To Reproduce**
1. activate the showrepaint plugin, observe the rendering box of the cursor when moving it.
![mpv-shot0001](https://github.com/user-attachments/assets/3ab6d635-fe8f-4fca-901e-ea2850defc4b)

**Expected behavior**
![mpv-shot0002](https://github.com/user-attachments/assets/4cc37d1d-a8e4-4353-b368-e72b8f3a41a8)

**Wayfire version**

0.8.1.r320.g7dfe9149-1

Related issues: 
https://github.com/hyprwm/Hyprland/issues/7577
https://gitlab.freedesktop.org/mesa/mesa/-/issues/11817
https://github.com/hyprwm/aquamarine/pull/71

**Comment by ammen99** [comment] 2024-10-09 13:21
Haven't looked very deeply into the hyprland issue but hw cursors are managed pretty much entirely in wlroots, there isn't much we can do about them.

I would try the PR for wlroots 0.18 support in Wayfire, if the issue is present in wlroots 0.18, then open an issue on the wlroots bug tracker.

**Comment by xiaohuirong** [comment] 2024-10-09 13:29
Thank you for your quick response. I will try to add the DRM_FORMAT_MOD_INVALID modifier to the cursor based on the Hyprland patch.

**Comment by xiaohuirong** [comment] 2024-10-09 15:30
I wrote the following patch, which fixes this issue.
```patch
diff --git a/render/allocator/gbm.c b/render/allocator/gbm.c
index da035c668..056c99ca6 100644
--- a/render/allocator/gbm.c
+++ b/render/allocator/gbm.c
@@ -113,7 +113,15 @@ static struct wlr_gbm_buffer *create_buffer(struct wlr_gbm_allocator *alloc,
 		errno = 0;
 		bo = gbm_bo_create(gbm_device, width, height, format->format, usage);
 		has_modifier = false;
+	} else {
+		uint64_t modifier = gbm_bo_get_modifier(bo);
+		if (format->len == 1 &&
+				format->modifiers[0] == DRM_FORMAT_MOD_LINEAR && modifier == DRM_FORMAT_MOD_INVALID) {
+			fallback_modifier = DRM_FORMAT_MOD_LINEAR;
+			has_modifier = false;
+		}
 	}
+
 	if (bo == NULL) {
 		wlr_log_errno(WLR_ERROR, "gbm_bo_create failed");
 		return NULL;

```

**Comment by soreau** [comment] 2024-10-09 15:48
Does it make a difference if you try running wayfire with `WLR_DRM_NO_MODIFIERS=1` set?

**Comment by xiaohuirong** [comment] 2024-10-09 16:04
The issue is still there

> Does it make a difference if you try running wayfire with `WLR_DRM_NO_MODIFIERS=1` set?

Adding this environment variable did not fix the issue.

**Comment by xiaohuirong** [comment] 2024-10-09 16:07
> It seems this is an issue that can be fixed in either wlroots or mesa, but not wayfire. I would recommend filing a report with wlroots and/or mesa.

Okay, I will file a report for wlroots.

**Comment by xiaohuirong** [comment] 2024-10-09 16:20
Here is the report sent to wlroots.
https://gitlab.freedesktop.org/mesa/mesa/-/issues/11817

**Comment by soreau** [comment] 2024-10-09 16:22
I think you mean:
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3905
👍

**Comment by soreau** [comment] 2024-11-28 15:22
Closing this since the problem was in mesa and a fix has been merged.

**Closed by soreau** 2024-11-28 15:22 UTC
Labels: bug

**Comment by xiaohuirong** [comment] 2024-11-29 03:17
> Closing this since the problem was in mesa and a fix has been merged.

Thanks!
