### ISSUE TITLE
Decoration plugin - minimize and maximize-restore buttons can not be activated when window maximized

### ISSUE THREAD

**Issue by mark-herbert42** [WayfireWM/wayfire#1819] opened 2023-07-02 18:03 UTC
With current git  version (transactions applied) - found that I can not restore window from maximized state using decoration buttons - only close red button active and can be clicked on maximized window while other buttons are gray and not clickable.

**Comment by mark-herbert42** [comment] 2023-07-02 19:14
Just found out - ithappens only if there is a panel (in my case xfce4-panel) on top of screen, that makes window maximize not to the top of the screen but to the edge of a panel. If I move the panel to bottom bug does not happen - buttons are activated fine and work.

**Comment by ammen99** [comment] 2023-08-01 18:57
Are you actually sure that the panel does not have shadows or similar which cover the buttons?

**Comment by mark-herbert42** [comment] 2023-08-05 05:44
Nothing visible at least.

**Comment by ammen99** [comment] 2023-08-20 10:28
I've been thinking, how do you even use xfce panel in Wayfire? It is a Xwayland app, so it will not work correctly (maximized windows will go under it, etc.)

> while other buttons are gray and not clickable.

Forgot to ask before: are you using the default decoration plugin, or one of the alternative plugins?

**Comment by mark-herbert42** [comment] 2023-08-21 04:11
With the latest patches of wayfire all alternative decorations stopped working - and even compiling is no more possible. So ony default decorator is possible.

As of xfce - those guys are moving forward to wayland port , and actually mentioned wayfire as a prefered compositor. So xfce panel does work, and what is even better it has tray applet working where indicator icons like messengerr, nm-applet and so on are available.  So as of now xfce-panel seems to be the best alternative - it allows whisker menu which combines pretty nice command louncher with nice hierarchical menu , it is configurable, it looks nice (waybar maybe less buggy and more native - but it is so fugly). Unfortunately xfce as a full set is not working under wayland yet  - only some components, I had xfce-panel (but coud not even start volume control applet and some other applets as well) and thunar which is from what I know is the only lightweight fm that run natively under wayland.

**Comment by ammen99** [comment] 2023-08-21 07:58
I installed xfce-panel from source (latest git) and started it. It seems to be working, but I cannot reproduce the bug, I can use all the buttons of a maximized window. Do you have any special configuration for xfce-panel? Does it support shadows or anything of the sort?

**Comment by ammen99** [comment] 2024-03-08 11:54
This might have been a bug in the panel you were testing. Closing for now, feel free to reopen if it still happens with newer versions of relevant software.

**Closed by ammen99** 2024-03-08 11:54 UTC
Labels: bug, needs information
