### ISSUE TITLE
Windows which are maximised and unmaximised can get their titlebars stuck under the panel

### ISSUE THREAD

**Issue by spl237** [WayfireWM/wayfire#1788] opened 2023-05-12 17:44 UTC
**Describe the bug**
If wf-panel is displayed at the top of the screen, and a window is dragged to the top of the screen, triggering a snap-to-maximized from the grid plugin, the window maxmizes. If the window is then unmaximized by double-clicking the titlebar, it reverts to the position immediately before the snap took place, which is with the window titlebar underneath the panel, meaning the window cannot then be moved and the titlebar controls are inaccessible.

**To Reproduce**
Run wf-panel at the top of the screen
Enable the grid plugin
Drag a window to the top of the screen so that a snap-to-maximized is triggered
Double-click the titlebar of the window to unmaximize
The titlebar of the window is now inaccessible

**Expected behavior**
I'd hope that a window can never be in a position where its titlebar is inaccessible; windows should be pushed out from under the panel in situations like this.

**More detail**
I tried to fix this by setting a rule in the window-rules plugin:
rule1 = on unmaximize then move 50 50

But this doesn't work - the window briefly moves to 50 50 when unmaximized, and then instantly moves to its original position with the titlebar obscured. If this could be made to work, then a rule like this would be a suitable workaround.

**Wayfire version**
0.7.5 from Debian bookworm

**Comment by ammen99** [comment] 2023-05-12 17:47
Sounds suboptimal, I agree. As a workaround (in case you haven't figured it out already), you can configure the move plugin, as with it you can start a window drag action by clicking anywhere on the window.

**Comment by ammen99** [comment] 2023-08-20 14:29
The problem is actually a duplicate of #1303, which was recently fixed. Now if you drag a window to the top to snap-maximize it, and then you unmaximize it from the button, it should restore to the original position where the window was before the first drag started.

**Closed by ammen99** 2023-08-20 14:29 UTC
Labels: bug
