### ISSUE TITLE
Cotton

### ISSUE THREAD

**Issue by cseyhua** [WayfireWM/wayfire#1749] opened 2023-03-02 15:57 UTC
version: 0.8.0
description: There is stuttering or high latency when using Expo

**Comment by ammen99** [comment] 2023-08-30 10:47
There were some improvements to Expo's animation since you opened this issue, is it still happening? If yes, what is your system, GPU, drivers, etc?

**Comment by ammen99** [comment] 2023-10-20 15:27
I suppose this is a duplicate of #1940, which has way more information on the issue, so closing this one.

**Closed by ammen99** 2023-10-20 15:27 UTC
Labels: bug
