### ISSUE TITLE
Mouse cursor invisible

### ISSUE THREAD

**Issue by mpolosak** [WayfireWM/wayfire#213] opened 2019-05-01 17:50 UTC
Mouse cursor is invisible when Wayfire runned as standalone Wayland session

**Comment by ammen99** [comment] 2019-05-01 18:53
Does the cursor work in rootston (the example compositor which comes with wlroots) or with Sway?

**Comment by AdrianVovk** [comment] 2019-05-02 04:11
I think I had this issue with nouveau. I didn't get to test further unfortunately to see if this is true

**Comment by soreau** [comment] 2019-05-02 04:12
Are there any relevant messages in the log?

**Comment by 256Michael** [comment] 2019-05-02 05:19
@ammen99 yes it works properly with Sway

**Comment by ammen99** [comment] 2019-05-02 09:15
@256Michael I guess that wf-shell or some other app is working at least?

**Comment by 256Michael** [comment] 2019-05-02 10:04
@ammen99 yes i use wf-shell

And this is log of Wayfire
[wayfire-log.txt](https://github.com/WayfireWM/wayfire/files/3137554/wayfire-log.txt)

**Comment by ammen99** [comment] 2019-05-02 11:06
@256Michael This problem seems very strange, since there are no errors in the config file which might be remotely related to this problem. This makes me a bit suspicious if this isn't a graphic related problem since we've tested Wayfire on mostly intel and radeon, but there should have been errors if that's the case.

Which version/commit of Wayfire are you using?

**Comment by damianatorrpm** [comment] 2020-04-11 13:04
I can confirm this, also with nouveau, works in sway.

**Comment by ammen99** [comment] 2020-04-11 13:06
@damianatorrpm Have you tried `WLR_NO_HARDWARE_CURSORS=1` before running wayfire?

**Comment by damianatorrpm** [comment] 2020-04-11 13:07
@ammen99 It works with WLR_NO_HARDWARE_CURSORS=1 just tried, you responded too fast!

**Comment by ammen99** [comment] 2020-04-11 13:09
Maybe sway exports this variable when it detects nouveau then. Closing this issue since I suspect that @mpolosak 's problem is the same.

**Closed by ammen99** 2020-04-11 13:09 UTC

**Comment by AdrianVovk** [comment] 2020-04-11 14:51
@ammen99 Wait why'd you close it? Wontfix?

**Comment by ammen99** [comment] 2020-04-11 15:20
@AdrianVovk But it works with the env var? I do not think it should be put inside Wayfire, even if Sway have done that.

**Comment by AdrianVovk** [comment] 2020-04-11 17:13
@ammen99 how would you expect an external program to figure out whether or not to set the env var outside of the display server?

**Comment by AdrianVovk** [comment] 2020-04-11 17:15
https://github.com/swaywm/sway/blob/525b48ede795effb6ef61b7caf6ad333393cfd64/sway/desktop/render.c#L1092
^ IDK enough about wlroots to say for sure but I think sway renders the software cursors always

**Comment by soreau** [comment] 2020-04-11 17:18
> @ammen99 how would you expect an external program to figure out whether or not to set the env var outside of the display server?

You could do something like [this wf-install PR](https://github.com/WayfireWM/wf-install/pull/9/commits/d5ff9bf722b3f9046c654b94603d0b661a85c5c7).

**Comment by ammen99** [comment] 2020-04-11 17:20
> @ammen99 how would you expect an external program to figure out whether or not to set the env var outside of the display server?

An external program would do it the same way as Wayfire would - check for the nouveau kernel module.



> https://github.com/swaywm/sway/blob/525b48ede795effb6ef61b7caf6ad333393cfd64/sway/desktop/render.c#L1092
> ^ IDK enough about wlroots to say for sure but I think sway renders the software cursors always

The way it works is that wlroots tries to create hardware cursors, and if that fails, it creates software cursors. In case hardware cursors are empty, the list of software cursors will be empty so that call is no-op in hw cursor case.

FWIW wayfire does exactly the same: https://github.com/WayfireWM/wayfire/blob/master/src/output/render-manager.cpp#L587

**Comment by ammen99** [comment] 2020-04-11 17:21
@damianatorrpm I wonder how it works in Sway when it does not seem to do anything related to the environmental variable ... Could it be that you have this env var set somewhere for Sway?

**Comment by damianatorrpm** [comment] 2020-04-12 07:42
Should be vanilla sway 1.4 `https://build.opensuse.org/package/show/X11:Wayland/sway`

```
tux@localhost:~> env | grep -i W
I3SOCK=/run/user/1000/sway-ipc.1000.30649.sock
DESKTOP_SESSION=sway
PWD=/home/tux
XDG_SESSION_DESKTOP=sway
XDG_SESSION_TYPE=wayland
LS_COLORS=(removed)
SWAYSOCK=/run/user/1000/sway-ipc.1000.30649.sock
WAYLAND_DISPLAY=wayland-0
GDMSESSION=sway
```

**Comment by damianatorrpm** [comment] 2020-04-23 06:52
@ammen99 
I think that if sway workaround this by autosetting this variable based on GPU detection,
wayfire should too.
For wayfire to work it is required otherwise to edit the file in `/usr/share/wayland-session` to point to a wrapper setting that environment variable.

 Changing things in root directory is hard for any immutable distros
> openSUSE Kubic, Fedora Silveblue, Clear Linux etc.

Another solution would be to use systemd.targets to handle startup of actual session. 
AFAIK systemd.targets can set environment variables in unit files depending on HW detection.

A sway example for a systemd handled session can be found here: 
https://github.com/b0o/sway-services
