### ISSUE TITLE
Keybindings ignore xkb_variant and default to qwerty.

### ISSUE THREAD

**Issue by g3r** [WayfireWM/wayfire#1091] opened 2021-02-15 13:26 UTC
**Describe the bug**
I use us dvorak layout:
```
[input]
xkb_layout = us
xkb_variant = dvorak
```
But keybindings need to be set in qwerty layout:
```
binding_bemenu = <super> KEY_H  #should be KEY_D
command_bemenu = bemenu-run
```
**Expected behavior**
Keybindings should respect selected layout.

**Comment by travankor** [comment] 2021-02-16 11:42
This is technically not a bug since wayfire was intentionally designed this way. Wayfire only cares about the actual hardware keycodes.

https://github.com/WayfireWM/wayfire/issues/403#issuecomment-737026657

**Comment by ammen99** [comment] 2021-03-02 21:40
> This is technically not a bug since wayfire was intentionally designed this way. Wayfire only cares about the actual hardware keycodes (assuming your hardware layout is qwerty).

Yes indeed, this is the case. I do not have any real interest in supporting bindings defined by the current layout, but will consider PRs if they do not break current configs.

**Comment by ammen99** [comment] 2023-12-14 07:58
Closing in favor of #1601

**Closed by ammen99** 2023-12-14 07:58 UTC
Labels: enhancement, low-priority
