### ISSUE TITLE
bindings to other languages

### ISSUE THREAD

**Issue by bijang** [WayfireWM/wayfire#479] opened 2020-04-18 21:54 UTC
apologies if this is inappropriate for this forum, I haven't much coding experience but I became interested in a very young commonlisp based WM project called mahogany https://github.com/stumpwm/mahogany which is essentially a rewrite in CommonLisp and C of StumpWM for wayland utilising wlroots, with a view for improved keybidings, speed etc, I raised an issue of themability to be a goal also, ie utilising effects that wouldn't be possible with the wlr lib and that's how I became aware of this amazing project... I am not involved in the construction of the base code, but how would one go about integrating wayfire compositor into this kind of project, can individual modules be used on top of wlr base or is there a more substantial code base that needs to be utilised? And are bindings to (in this case) lisp easy to achieve, so a lisp wrapper can be used as the interface to the internals?
Please delete this if it is felt to be inappropriate, I'm just very pleased this project exists (and wish I knew more about coding)!

**Comment by ammen99** [comment] 2020-04-18 22:06
Hi, parts of Wayfire cannot be easily used in other window managers, because Wayfire's core provides many APIs not present elsewhere. If you want to use tiling and the other benefits of Wayfire, you could try to check out the simple-tile plugin. It is a little similar to the pointer-based i3 tiling, however there aren't many keyboard shortcuts for changing the layout (everything is done with the mouse).

On the topic of C bindings (and then you could interop with Lips and most other languages), we have an issue for that: #48 . I am not personally interested in this, so I am not going to implement C bindings myself anytime soon. However, if someone were willing to work on that, I'm ready to give a few tips about where to start, and to fix any potential issues in the core.

Closing this issue since it is essentially a duplicate of #48.

**Closed by ammen99** 2020-04-18 22:06 UTC
