### ISSUE TITLE
Poor experience using Renoise 3.4.3 on Raspberry Pi 64bit Bookworm | Wayfire 0.7.5

### ISSUE THREAD

**Issue by rrymc** [WayfireWM/wayfire#2010] opened 2023-11-08 20:32 UTC
**Describe the bug**
Renoise 3.4.3 on Pi OS 64bit Bookworm on RPi4B / Pi400 (latest release, fully updated at time of writing) doesn’t appear in the native window manager and am unable to move the window containing Renoise around the screen. It is locked to one position on the screen.

You can full screen, minimise, and you can drag to increase size of the Renoise window, but you can’t move the window around, and Renoise doesn’t appear to be windowed in the native window style.

Windows that open within the program open incorrectly, and moving these windows around includes the windows flickering around the screen as I move them, and has overall sluggish / glitchy handling.

**To Reproduce**
1. Open Renoise

**Expected behavior**
I would expect to be able to cleanly open/close/resize/move windows, and for this to happen smoothly and without position glitching.

**Screenshots**

Unable to move the Renoise window (left) displayed in this screenshot. No native window bordering. See small window on right of screen for expected window bordering. That one (qjackctl) is fine.
![initial window state](https://github.com/WayfireWM/wayfire/assets/150283102/76665122-e591-412a-a79d-71102545278d)

**Wayfire version**
0.7.5

**Comment by soreau** [comment] 2023-11-08 20:37
It is possible that the experience is better in 0.8 release or even master branch. Are you able to test?

**Comment by ammen99** [comment] 2023-11-08 20:40
Seems like Renoise uses custom CSD. It is also quite possible that it does not use the standard interface for window dragging, but tries to update its position manually to follow the mouse (which Wayfire does not allow). In that case, the problem would be a duplicate of #953 . I am not sure how to verify this though.

**Comment by soreau** [comment] 2023-11-08 22:47
> Seems like Renoise uses custom CSD. It is also quite possible that it does not use the standard interface for window dragging, but tries to update its position manually to follow the mouse (which Wayfire does not allow). In that case, the problem would be a duplicate of #953 . I am not sure how to verify this though.

If this is the case, maybe mod+drag to move the window? [<super>+BTN_LEFT](https://github.com/WayfireWM/wayfire/blob/master/metadata/move.xml#L10) by default

**Comment by rrymc** [comment] 2023-11-09 07:12
> It is possible that the experience is better in 0.8 release or even master branch. Are you able to test?

I would only say I'm a casual Linux user :) 'sudo apt-get install wayfire' tells me I'm on the latest version (0.7.5-1~bpo11+1~rpt27), how would I go about using a newer version? Do I need to install a repo? Thanks.

**Comment by ammen99** [comment] 2023-11-09 08:44
You'll have to install Wayfire from source afaik. Check out wf-install if you opt for this, but keep in mind that rpi os-specific plugins won't work... Also, if I am right, at least some of the issues won't be solved.

I'd recommend checking out soreau's suggestion, moving with the binding from the move plugin.

**Comment by rrymc** [comment] 2023-11-09 17:46
> > Seems like Renoise uses custom CSD. It is also quite possible that it does not use the standard interface for window dragging, but tries to update its position manually to follow the mouse (which Wayfire does not allow). In that case, the problem would be a duplicate of #953 . I am not sure how to verify this though.
> 
> If this is the case, maybe mod+drag to move the window? [<super>+BTN_LEFT](https://github.com/WayfireWM/wayfire/blob/master/metadata/move.xml#L10) by default

Yes, using the super key does allow the main window to be moved.

**Comment by ammen99** [comment] 2023-11-29 21:35
To me, this sounds like a duplicate of #953, closing (unless someone figures out that Wayfire indeed does something wrong).

**Closed by ammen99** 2023-11-29 21:35 UTC
Labels: bug
