### ISSUE TITLE
Black screen on waydroid

### ISSUE THREAD

**Issue by Quackdoc** [WayfireWM/wayfire#1615] opened 2022-11-13 17:11 UTC
**Describe the bug**

When running `waydroid show-full-ui` the resulting window is black, when dragging the screen to the top of window to auto resize, it briefly shows the content of the screen, touch and keyboard is being passed through to the android container perfectly fine

**To Reproduce**
1. Install waydroid
2. run waydroid with `waydroid show-full-ui`

**Expected behavior**
Waydroid should open a fullscreen android container

**Screenshots or stacktrace**
N/A also running WAYLAND_DEBUG with waydroid produces no output at this time

**Wayfire version**
wayfire-git 0.7.4.r341.g866cdf28-1

**Additional Info**
Originally though to be a wlroots issue, turns out it isn't has been successfully tested on both sway and cage installed side by side with wayfire. 

the screen manages to flicker when snapping and unsnapping from edges

**Comment by Quronox** [comment] 2022-11-23 20:29
Same here - while the apps themselves seems to work - clicking on icons and buttons result in expected behavior. Just can't see anything :<

**Comment by soreau** [comment] 2022-11-23 20:31
Does this work on sway?

**Comment by Quackdoc** [comment] 2022-11-24 05:58
It does indeed work on sway last I checked though I should be able to check again shortly

**Comment by tombh** [comment] 2022-11-26 01:08
Exactly the same issue. Waydroid is mostly a black screen, certain interactions, like fullscreening, make it flash visible for a moment. So I'm able to see that it does work.

I can confirm it works in Hyprland, another wlroots-based WM.

**Comment by Quronox** [comment] 2022-11-30 21:05
Got an update on this - it's working on my wayfire now, the last change that I remember was to enable the "blur" plugin.
Can anyone confirm that enabling the blur plugin with the property "blur_by_default = all" and "method = kawase" changes this behavior?

**Comment by soreau** [comment] 2022-11-30 21:08
@Quronox Enabling the blur plugin is not likely to affect anything. I have it enabled with the same settings as you describe and it makes no difference. Can you upload your wayfire.ini file?

**Comment by Quronox** [comment] 2022-11-30 21:47
[wayfire.ini.zip](https://github.com/WayfireWM/wayfire/files/10127554/wayfire.ini.zip)

**Comment by Quackdoc** [comment] 2022-12-01 14:33
I tried using the blur plugin and it didn't work out for me personally 
[here is my config if it would help crosscheck](https://github.com/WayfireWM/wayfire/files/10133244/wayfire.txt)

**Comment by Quronox** [comment] 2022-12-01 20:00
Well, just in case it helps to trace this:

Another change was to enable the dbus plugin:
https://github.com/damianatorrpm/wayfire-plugin_dbus_interface

Screenshot with confirmation that it works for real:
![image](https://user-images.githubusercontent.com/41745459/205147860-ad58c417-c491-4f1d-a8ff-a86e5acb5c11.png)

**Comment by jirihalbych** [comment] 2023-01-12 19:05
Enabled both blur and dbus plugins, neither of them fixed the issue

**Comment by prehonor** [comment] 2023-01-15 14:57
I have some issure, waydroid works in hyprland but not in wayfire

**Comment by prehonor** [comment] 2023-01-15 15:04
> Enabled both blur and dbus plugins, neither of them fixed the issue

My wayfire follow master branches until now.I can' t compile [wayfire-plugin_dbus_interface](https://github.com/damianatorrpm/wayfire-plugin_dbus_interface) ,so I wait for answer.

**Comment by soreau** [comment] 2023-01-17 03:33
Using `waydroid prop set persist.waydroid.multi_windows true` while the session is running and restarting waydroid makes it work so it seems this is a client bug. Closing for now.

**Comment by drwankingstein** [comment] 2023-01-23 06:50
I highly disagree with this conclusion, it works on weston, gnome, kde,  and as for wlroots compositors sway, cage and according to another user in this thread hyprland. the issue seems specific to wayfire.

**Comment by tombh** [comment] 2023-01-23 14:27
Whilst I sympathise with the argument that wayfire _could_ take responsibility for this, I think it could be expressed more constructively. Eg;

Thank you Soreau for looking into this and providing us with a fix. I would just like to make a note that it may be worth revisiting this issue when you or anybody else has time. It seems that the majority of other Wayland clients do not need such manual intervention.

**Comment by Boruch-Baum** [comment] 2023-03-14 06:05
I'm able to use waydroid using weston inside plasma-X11, but in a direct plasma-wayland session, I also get this black screen issue, with the same momentary correct screen display for an instant when killing the window.

**Comment by Boruch-Baum** [comment] 2023-03-14 06:17
Just tested in a sway session, and waydroid displays correctly there also, so for me the problem is only in a direct plasma-wayland session

**Comment by th3cr00k3dm4n** [comment] 2023-04-22 05:28
any solution for this

**Comment by bhlevca** [comment] 2023-11-10 04:26
Any progress on this bug?

**Comment by Botspot** [comment] 2024-01-17 05:06
This is still a bug that only occurs on Wayfire. The black screen problem does not occur on Weston or other similar wayland sessions.
See: https://github.com/waydroid/waydroid/issues/1171#issuecomment-1877916174

This issue here should re-opened, or at the very least, re-investigated. Waydroid is very useful, and we should not have to leave behind wayfire for it to work.

**Comment by Botspot** [comment] 2024-01-17 05:09
@soreau could this be re-investigated, or could you at least try to communicate with the waydroid devs to show them the "client bug" you speak of?

**Comment by soreau** [comment] 2024-01-17 05:16
I have reinvestigated this and I think now it's the same as [#1206](https://github.com/WayfireWM/wayfire/issues/1206). [This part of the code](https://github.com/WayfireWM/wayfire/blob/master/src/view/surface.cpp#L48) needs a condition to branch to `add_back()` when necessary but so far, I'm unsure how to find this information from wlroots.

**Comment by soreau** [comment] 2024-01-17 05:46
@Botspot Does [this patch](https://termbin.com/ttw9) help?

**Comment by Botspot** [comment] 2024-01-17 05:59
> @Botspot Does [this patch](https://termbin.com/ttw9) help?

I am using [the fork of wayfire used on Raspberry Pi OS](https://github.com/raspberrypi-ui/wayfire), so I think that means I cannot directly apply your patch. I will forward your patch to the others on [this issue](https://github.com/waydroid/waydroid/issues/1171) to see if one of them would like to try the patch.

**Closed** 2024-01-17 21:20 UTC
Labels: bug
