### ISSUE TITLE
Firefox Wayland find-in-page dialog causes shell to crash

### ISSUE THREAD

**Issue by kode54** [WayfireWM/wayfire#603] opened 2020-07-20 04:01 UTC
The find-in-page (ctrl-f) dialog in Firefox in Wayland mode can cause the entire shell to crash back to my display manager. I can generate a Wayfire log from launching a session from a TTY if necessary.

**Comment by soreau** [comment] 2020-07-20 04:13
When I use ctrl+f in firefox nightly, it shows a find bar in the bottom of the window. What dialog are you talking about? What firefox and wayfire versions are you using?

**Comment by kode54** [comment] 2020-07-20 04:20
With latest git packages of everything, possibly impacted by that game/minimize patch set, when I use ctrl-f find, and type more than two nonsense characters, it crashes Wayfire.

**Comment by soreau** [comment] 2020-07-20 04:23
This is not a bug in wayfire upstream but with #552 patch. Closing.

**Closed by soreau** 2020-07-20 04:23 UTC
