### ISSUE TITLE
Grabbing window with <super>+single left click doesn't bring it forward.

### ISSUE THREAD

**Issue by k9spud** [WayfireWM/wayfire#1118] opened 2021-03-14 16:24 UTC
**Grabbing window with [super]+single left click doesn't bring it forward.**

When I want to bring a window forward to display itself on top of all the other windows, I often use the grab feature of my old window manager by holding down the [super] key and then single left click in the window. 

In Wayfire, there is a grab feature, but unfortunately, unless I actually move the window when I grab it, Wayfire puts the window back down to it's original Z-position (behind other windows) as soon as I release the mouse button. It shouldn't do that.

Someone might ask, "Well, why don't you just left click without holding down [super]?" 

The problem with simply left clicking is that you might accidentally click on a button or link inside the window, making that app go do something you didn't want it to do. By holding down [super], you're telling the window manager to NOT forward the left click event into the client, which is _very helpful_ when you're trying to bring a window forward to look at it more carefully before performing any actions.

**To Reproduce**
1. Stack a bunch of windows overlapping each other.
2. Hold down [super] and single left click on one of the windows that is being largely hidden by windows in front of it. Do not move the mouse.
3. Window will briefly flicker to the front, then fall back down to it's original Z-order once the left mouse button has been released.

**Expected behavior**
Window should stay on top.

**Wayfire version**
0.7.0

**Comment by ammen99** [comment] 2021-03-14 19:11
I can reproduce, this is an interesting bug. Will fix this for the next release.

**Comment by soreau** [comment] 2022-10-12 19:58
I can't reproduce this with latest master, can anyone else?

**Comment by ammen99** [comment] 2023-06-26 13:01
Seems to work nowadays, closing.

**Closed by ammen99** 2023-06-26 13:01 UTC
Labels: bug

**Comment by k9spud** [comment] 2023-10-26 09:51
Now that 0.8.0 is released, I had a chance to test this. It works much better now, but I still have the problem when the window underneath happens to be in a maximized state. So, I'd say this bug is not fully resolved.

**Comment by ammen99** [comment] 2023-10-26 11:03
There are a few core options which might help you achieve this (they were previously not in the wiki, I just added them): https://github.com/WayfireWM/wayfire/wiki/Configuration#corefocus_button_with_modifiers

The reason for the behavior you are currently seeing is that fullscreen and/or maximized views are not really moved until a certain threshold is exceeded. This is controlled by `move/enable_snap_off`.

**Comment by k9spud** [comment] 2023-10-26 23:24
I set "snap_off_threshold = 0" in the [move] section of my wayfire.ini and now it works correctly. Thanks!
